server:
  port: 8080

spring:
  application:
    name: learn-from-claude
  datasource:
    url: jdbc:postgresql://192.168.20.129:5432/ragdb
    username: pgsql
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql


# application.yml
#langchain4j:
#  openai:              # ← 不是 open-ai
#    chat-model:
#      base-url: https://api.deepseek.com
#      api-key: ${DEEPSEEK_API_KEY}
#      model-name: deepseek-chat

